services:
  - type: web
    name: tourbnb-backend
    runtime: node
    plan: free
    buildCommand: npm install && npm run build && npx prisma migrate deploy
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        scope: build,runtime
      - key: JWT_SECRET
        scope: runtime
      - key: NODE_ENV
        value: production
